/**
 * Copyright 2019 Bart Butenaers, Stephen McLaughlin
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 **/
exports.getUnicode = function(iconCssClass) {
    // See https://fontawesome.com/v4.7.0/cheatsheet/
    // This file has been converted from https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css
    switch(iconCssClass) {
        case "fa-glass":
            return "f000";
        case "fa-music":
            return "f001";
        case "fa-search":
            return "f002";
        case "fa-envelope-o":
            return "f003";
        case "fa-heart":
            return "f004";
        case "fa-star":
            return "f005";
        case "fa-star-o":
            return "f006";
        case "fa-user":
            return "f007";
        case "fa-film":
            return "f008";
        case "fa-th-large":
            return "f009";
        case "fa-th":
            return "f00a";
        case "fa-th-list":
            return "f00b";
        case "fa-check":
            return "f00c";
        case "fa-remove:before,.fa-close:before,.fa-times":
            return "f00d";
        case "fa-search-plus":
            return "f00e";
        case "fa-search-minus":
            return "f010";
        case "fa-power-off":
            return "f011";
        case "fa-signal":
            return "f012";
        case "fa-gear:before,.fa-cog":
            return "f013";
        case "fa-trash-o":
            return "f014";
        case "fa-home":
            return "f015";
        case "fa-file-o":
            return "f016";
        case "fa-clock-o":
            return "f017";
        case "fa-road":
            return "f018";
        case "fa-download":
            return "f019";
        case "fa-arrow-circle-o-down":
            return "f01a";
        case "fa-arrow-circle-o-up":
            return "f01b";
        case "fa-inbox":
            return "f01c";
        case "fa-play-circle-o":
            return "f01d";
        case "fa-rotate-right:before,.fa-repeat":
            return "f01e";
        case "fa-refresh":
            return "f021";
        case "fa-list-alt":
            return "f022";
        case "fa-lock":
            return "f023";
        case "fa-flag":
            return "f024";
        case "fa-headphones":
            return "f025";
        case "fa-volume-off":
            return "f026";
        case "fa-volume-down":
            return "f027";
        case "fa-volume-up":
            return "f028";
        case "fa-qrcode":
            return "f029";
        case "fa-barcode":
            return "f02a";
        case "fa-tag":
            return "f02b";
        case "fa-tags":
            return "f02c";
        case "fa-book":
            return "f02d";
        case "fa-bookmark":
            return "f02e";
        case "fa-print":
            return "f02f";
        case "fa-camera":
            return "f030";
        case "fa-font":
            return "f031";
        case "fa-bold":
            return "f032";
        case "fa-italic":
            return "f033";
        case "fa-text-height":
            return "f034";
        case "fa-text-width":
            return "f035";
        case "fa-align-left":
            return "f036";
        case "fa-align-center":
            return "f037";
        case "fa-align-right":
            return "f038";
        case "fa-align-justify":
            return "f039";
        case "fa-list":
            return "f03a";
        case "fa-dedent:before,.fa-outdent":
            return "f03b";
        case "fa-indent":
            return "f03c";
        case "fa-video-camera":
            return "f03d";
        case "fa-photo:before,.fa-image:before,.fa-picture-o":
            return "f03e";
        case "fa-pencil":
            return "f040";
        case "fa-map-marker":
            return "f041";
        case "fa-adjust":
            return "f042";
        case "fa-tint":
            return "f043";
        case "fa-edit:before,.fa-pencil-square-o":
            return "f044";
        case "fa-share-square-o":
            return "f045";
        case "fa-check-square-o":
            return "f046";
        case "fa-arrows":
            return "f047";
        case "fa-step-backward":
            return "f048";
        case "fa-fast-backward":
            return "f049";
        case "fa-backward":
            return "f04a";
        case "fa-play":
            return "f04b";
        case "fa-pause":
            return "f04c";
        case "fa-stop":
            return "f04d";
        case "fa-forward":
            return "f04e";
        case "fa-fast-forward":
            return "f050";
        case "fa-step-forward":
            return "f051";
        case "fa-eject":
            return "f052";
        case "fa-chevron-left":
            return "f053";
        case "fa-chevron-right":
            return "f054";
        case "fa-plus-circle":
            return "f055";
        case "fa-minus-circle":
            return "f056";
        case "fa-times-circle":
            return "f057";
        case "fa-check-circle":
            return "f058";
        case "fa-question-circle":
            return "f059";
        case "fa-info-circle":
            return "f05a";
        case "fa-crosshairs":
            return "f05b";
        case "fa-times-circle-o":
            return "f05c";
        case "fa-check-circle-o":
            return "f05d";
        case "fa-ban":
            return "f05e";
        case "fa-arrow-left":
            return "f060";
        case "fa-arrow-right":
            return "f061";
        case "fa-arrow-up":
            return "f062";
        case "fa-arrow-down":
            return "f063";
        case "fa-mail-forward:before,.fa-share":
            return "f064";
        case "fa-expand":
            return "f065";
        case "fa-compress":
            return "f066";
        case "fa-plus":
            return "f067";
        case "fa-minus":
            return "f068";
        case "fa-asterisk":
            return "f069";
        case "fa-exclamation-circle":
            return "f06a";
        case "fa-gift":
            return "f06b";
        case "fa-leaf":
            return "f06c";
        case "fa-fire":
            return "f06d";
        case "fa-eye":
            return "f06e";
        case "fa-eye-slash":
            return "f070";
        case "fa-warning:before,.fa-exclamation-triangle":
            return "f071";
        case "fa-plane":
            return "f072";
        case "fa-calendar":
            return "f073";
        case "fa-random":
            return "f074";
        case "fa-comment":
            return "f075";
        case "fa-magnet":
            return "f076";
        case "fa-chevron-up":
            return "f077";
        case "fa-chevron-down":
            return "f078";
        case "fa-retweet":
            return "f079";
        case "fa-shopping-cart":
            return "f07a";
        case "fa-folder":
            return "f07b";
        case "fa-folder-open":
            return "f07c";
        case "fa-arrows-v":
            return "f07d";
        case "fa-arrows-h":
            return "f07e";
        case "fa-bar-chart-o:before,.fa-bar-chart":
            return "f080";
        case "fa-twitter-square":
            return "f081";
        case "fa-facebook-square":
            return "f082";
        case "fa-camera-retro":
            return "f083";
        case "fa-key":
            return "f084";
        case "fa-gears:before,.fa-cogs":
            return "f085";
        case "fa-comments":
            return "f086";
        case "fa-thumbs-o-up":
            return "f087";
        case "fa-thumbs-o-down":
            return "f088";
        case "fa-star-half":
            return "f089";
        case "fa-heart-o":
            return "f08a";
        case "fa-sign-out":
            return "f08b";
        case "fa-linkedin-square":
            return "f08c";
        case "fa-thumb-tack":
            return "f08d";
        case "fa-external-link":
            return "f08e";
        case "fa-sign-in":
            return "f090";
        case "fa-trophy":
            return "f091";
        case "fa-github-square":
            return "f092";
        case "fa-upload":
            return "f093";
        case "fa-lemon-o":
            return "f094";
        case "fa-phone":
            return "f095";
        case "fa-square-o":
            return "f096";
        case "fa-bookmark-o":
            return "f097";
        case "fa-phone-square":
            return "f098";
        case "fa-twitter":
            return "f099";
        case "fa-facebook-f:before,.fa-facebook":
            return "f09a";
        case "fa-github":
            return "f09b";
        case "fa-unlock":
            return "f09c";
        case "fa-credit-card":
            return "f09d";
        case "fa-feed:before,.fa-rss":
            return "f09e";
        case "fa-hdd-o":
            return "f0a0";
        case "fa-bullhorn":
            return "f0a1";
        case "fa-bell":
            return "f0f3";
        case "fa-certificate":
            return "f0a3";
        case "fa-hand-o-right":
            return "f0a4";
        case "fa-hand-o-left":
            return "f0a5";
        case "fa-hand-o-up":
            return "f0a6";
        case "fa-hand-o-down":
            return "f0a7";
        case "fa-arrow-circle-left":
            return "f0a8";
        case "fa-arrow-circle-right":
            return "f0a9";
        case "fa-arrow-circle-up":
            return "f0aa";
        case "fa-arrow-circle-down":
            return "f0ab";
        case "fa-globe":
            return "f0ac";
        case "fa-wrench":
            return "f0ad";
        case "fa-tasks":
            return "f0ae";
        case "fa-filter":
            return "f0b0";
        case "fa-briefcase":
            return "f0b1";
        case "fa-arrows-alt":
            return "f0b2";
        case "fa-group:before,.fa-users":
            return "f0c0";
        case "fa-chain:before,.fa-link":
            return "f0c1";
        case "fa-cloud":
            return "f0c2";
        case "fa-flask":
            return "f0c3";
        case "fa-cut:before,.fa-scissors":
            return "f0c4";
        case "fa-copy:before,.fa-files-o":
            return "f0c5";
        case "fa-paperclip":
            return "f0c6";
        case "fa-save:before,.fa-floppy-o":
            return "f0c7";
        case "fa-square":
            return "f0c8";
        case "fa-navicon:before,.fa-reorder:before,.fa-bars":
            return "f0c9";
        case "fa-list-ul":
            return "f0ca";
        case "fa-list-ol":
            return "f0cb";
        case "fa-strikethrough":
            return "f0cc";
        case "fa-underline":
            return "f0cd";
        case "fa-table":
            return "f0ce";
        case "fa-magic":
            return "f0d0";
        case "fa-truck":
            return "f0d1";
        case "fa-pinterest":
            return "f0d2";
        case "fa-pinterest-square":
            return "f0d3";
        case "fa-google-plus-square":
            return "f0d4";
        case "fa-google-plus":
            return "f0d5";
        case "fa-money":
            return "f0d6";
        case "fa-caret-down":
            return "f0d7";
        case "fa-caret-up":
            return "f0d8";
        case "fa-caret-left":
            return "f0d9";
        case "fa-caret-right":
            return "f0da";
        case "fa-columns":
            return "f0db";
        case "fa-unsorted:before,.fa-sort":
            return "f0dc";
        case "fa-sort-down:before,.fa-sort-desc":
            return "f0dd";
        case "fa-sort-up:before,.fa-sort-asc":
            return "f0de";
        case "fa-envelope":
            return "f0e0";
        case "fa-linkedin":
            return "f0e1";
        case "fa-rotate-left:before,.fa-undo":
            return "f0e2";
        case "fa-legal:before,.fa-gavel":
            return "f0e3";
        case "fa-dashboard:before,.fa-tachometer":
            return "f0e4";
        case "fa-comment-o":
            return "f0e5";
        case "fa-comments-o":
            return "f0e6";
        case "fa-flash:before,.fa-bolt":
            return "f0e7";
        case "fa-sitemap":
            return "f0e8";
        case "fa-umbrella":
            return "f0e9";
        case "fa-paste:before,.fa-clipboard":
            return "f0ea";
        case "fa-lightbulb-o":
            return "f0eb";
        case "fa-exchange":
            return "f0ec";
        case "fa-cloud-download":
            return "f0ed";
        case "fa-cloud-upload":
            return "f0ee";
        case "fa-user-md":
            return "f0f0";
        case "fa-stethoscope":
            return "f0f1";
        case "fa-suitcase":
            return "f0f2";
        case "fa-bell-o":
            return "f0a2";
        case "fa-coffee":
            return "f0f4";
        case "fa-cutlery":
            return "f0f5";
        case "fa-file-text-o":
            return "f0f6";
        case "fa-building-o":
            return "f0f7";
        case "fa-hospital-o":
            return "f0f8";
        case "fa-ambulance":
            return "f0f9";
        case "fa-medkit":
            return "f0fa";
        case "fa-fighter-jet":
            return "f0fb";
        case "fa-beer":
            return "f0fc";
        case "fa-h-square":
            return "f0fd";
        case "fa-plus-square":
            return "f0fe";
        case "fa-angle-double-left":
            return "f100";
        case "fa-angle-double-right":
            return "f101";
        case "fa-angle-double-up":
            return "f102";
        case "fa-angle-double-down":
            return "f103";
        case "fa-angle-left":
            return "f104";
        case "fa-angle-right":
            return "f105";
        case "fa-angle-up":
            return "f106";
        case "fa-angle-down":
            return "f107";
        case "fa-desktop":
            return "f108";
        case "fa-laptop":
            return "f109";
        case "fa-tablet":
            return "f10a";
        case "fa-mobile-phone:before,.fa-mobile":
            return "f10b";
        case "fa-circle-o":
            return "f10c";
        case "fa-quote-left":
            return "f10d";
        case "fa-quote-right":
            return "f10e";
        case "fa-spinner":
            return "f110";
        case "fa-circle":
            return "f111";
        case "fa-mail-reply:before,.fa-reply":
            return "f112";
        case "fa-github-alt":
            return "f113";
        case "fa-folder-o":
            return "f114";
        case "fa-folder-open-o":
            return "f115";
        case "fa-smile-o":
            return "f118";
        case "fa-frown-o":
            return "f119";
        case "fa-meh-o":
            return "f11a";
        case "fa-gamepad":
            return "f11b";
        case "fa-keyboard-o":
            return "f11c";
        case "fa-flag-o":
            return "f11d";
        case "fa-flag-checkered":
            return "f11e";
        case "fa-terminal":
            return "f120";
        case "fa-code":
            return "f121";
        case "fa-mail-reply-all:before,.fa-reply-all":
            return "f122";
        case "fa-star-half-empty:before,.fa-star-half-full:before,.fa-star-half-o":
            return "f123";
        case "fa-location-arrow":
            return "f124";
        case "fa-crop":
            return "f125";
        case "fa-code-fork":
            return "f126";
        case "fa-unlink:before,.fa-chain-broken":
            return "f127";
        case "fa-question":
            return "f128";
        case "fa-info":
            return "f129";
        case "fa-exclamation":
            return "f12a";
        case "fa-superscript":
            return "f12b";
        case "fa-subscript":
            return "f12c";
        case "fa-eraser":
            return "f12d";
        case "fa-puzzle-piece":
            return "f12e";
        case "fa-microphone":
            return "f130";
        case "fa-microphone-slash":
            return "f131";
        case "fa-shield":
            return "f132";
        case "fa-calendar-o":
            return "f133";
        case "fa-fire-extinguisher":
            return "f134";
        case "fa-rocket":
            return "f135";
        case "fa-maxcdn":
            return "f136";
        case "fa-chevron-circle-left":
            return "f137";
        case "fa-chevron-circle-right":
            return "f138";
        case "fa-chevron-circle-up":
            return "f139";
        case "fa-chevron-circle-down":
            return "f13a";
        case "fa-html5":
            return "f13b";
        case "fa-css3":
            return "f13c";
        case "fa-anchor":
            return "f13d";
        case "fa-unlock-alt":
            return "f13e";
        case "fa-bullseye":
            return "f140";
        case "fa-ellipsis-h":
            return "f141";
        case "fa-ellipsis-v":
            return "f142";
        case "fa-rss-square":
            return "f143";
        case "fa-play-circle":
            return "f144";
        case "fa-ticket":
            return "f145";
        case "fa-minus-square":
            return "f146";
        case "fa-minus-square-o":
            return "f147";
        case "fa-level-up":
            return "f148";
        case "fa-level-down":
            return "f149";
        case "fa-check-square":
            return "f14a";
        case "fa-pencil-square":
            return "f14b";
        case "fa-external-link-square":
            return "f14c";
        case "fa-share-square":
            return "f14d";
        case "fa-compass":
            return "f14e";
        case "fa-toggle-down:before,.fa-caret-square-o-down":
            return "f150";
        case "fa-toggle-up:before,.fa-caret-square-o-up":
            return "f151";
        case "fa-toggle-right:before,.fa-caret-square-o-right":
            return "f152";
        case "fa-euro:before,.fa-eur":
            return "f153";
        case "fa-gbp":
            return "f154";
        case "fa-dollar:before,.fa-usd":
            return "f155";
        case "fa-rupee:before,.fa-inr":
            return "f156";
        case "fa-cny:before,.fa-rmb:before,.fa-yen:before,.fa-jpy":
            return "f157";
        case "fa-ruble:before,.fa-rouble:before,.fa-rub":
            return "f158";
        case "fa-won:before,.fa-krw":
            return "f159";
        case "fa-bitcoin:before,.fa-btc":
            return "f15a";
        case "fa-file":
            return "f15b";
        case "fa-file-text":
            return "f15c";
        case "fa-sort-alpha-asc":
            return "f15d";
        case "fa-sort-alpha-desc":
            return "f15e";
        case "fa-sort-amount-asc":
            return "f160";
        case "fa-sort-amount-desc":
            return "f161";
        case "fa-sort-numeric-asc":
            return "f162";
        case "fa-sort-numeric-desc":
            return "f163";
        case "fa-thumbs-up":
            return "f164";
        case "fa-thumbs-down":
            return "f165";
        case "fa-youtube-square":
            return "f166";
        case "fa-youtube":
            return "f167";
        case "fa-xing":
            return "f168";
        case "fa-xing-square":
            return "f169";
        case "fa-youtube-play":
            return "f16a";
        case "fa-dropbox":
            return "f16b";
        case "fa-stack-overflow":
            return "f16c";
        case "fa-instagram":
            return "f16d";
        case "fa-flickr":
            return "f16e";
        case "fa-adn":
            return "f170";
        case "fa-bitbucket":
            return "f171";
        case "fa-bitbucket-square":
            return "f172";
        case "fa-tumblr":
            return "f173";
        case "fa-tumblr-square":
            return "f174";
        case "fa-long-arrow-down":
            return "f175";
        case "fa-long-arrow-up":
            return "f176";
        case "fa-long-arrow-left":
            return "f177";
        case "fa-long-arrow-right":
            return "f178";
        case "fa-apple":
            return "f179";
        case "fa-windows":
            return "f17a";
        case "fa-android":
            return "f17b";
        case "fa-linux":
            return "f17c";
        case "fa-dribbble":
            return "f17d";
        case "fa-skype":
            return "f17e";
        case "fa-foursquare":
            return "f180";
        case "fa-trello":
            return "f181";
        case "fa-female":
            return "f182";
        case "fa-male":
            return "f183";
        case "fa-gittip:before,.fa-gratipay":
            return "f184";
        case "fa-sun-o":
            return "f185";
        case "fa-moon-o":
            return "f186";
        case "fa-archive":
            return "f187";
        case "fa-bug":
            return "f188";
        case "fa-vk":
            return "f189";
        case "fa-weibo":
            return "f18a";
        case "fa-renren":
            return "f18b";
        case "fa-pagelines":
            return "f18c";
        case "fa-stack-exchange":
            return "f18d";
        case "fa-arrow-circle-o-right":
            return "f18e";
        case "fa-arrow-circle-o-left":
            return "f190";
        case "fa-toggle-left:before,.fa-caret-square-o-left":
            return "f191";
        case "fa-dot-circle-o":
            return "f192";
        case "fa-wheelchair":
            return "f193";
        case "fa-vimeo-square":
            return "f194";
        case "fa-turkish-lira:before,.fa-try":
            return "f195";
        case "fa-plus-square-o":
            return "f196";
        case "fa-space-shuttle":
            return "f197";
        case "fa-slack":
            return "f198";
        case "fa-envelope-square":
            return "f199";
        case "fa-wordpress":
            return "f19a";
        case "fa-openid":
            return "f19b";
        case "fa-institution:before,.fa-bank:before,.fa-university":
            return "f19c";
        case "fa-mortar-board:before,.fa-graduation-cap":
            return "f19d";
        case "fa-yahoo":
            return "f19e";
        case "fa-google":
            return "f1a0";
        case "fa-reddit":
            return "f1a1";
        case "fa-reddit-square":
            return "f1a2";
        case "fa-stumbleupon-circle":
            return "f1a3";
        case "fa-stumbleupon":
            return "f1a4";
        case "fa-delicious":
            return "f1a5";
        case "fa-digg":
            return "f1a6";
        case "fa-pied-piper-pp":
            return "f1a7";
        case "fa-pied-piper-alt":
            return "f1a8";
        case "fa-drupal":
            return "f1a9";
        case "fa-joomla":
            return "f1aa";
        case "fa-language":
            return "f1ab";
        case "fa-fax":
            return "f1ac";
        case "fa-building":
            return "f1ad";
        case "fa-child":
            return "f1ae";
        case "fa-paw":
            return "f1b0";
        case "fa-spoon":
            return "f1b1";
        case "fa-cube":
            return "f1b2";
        case "fa-cubes":
            return "f1b3";
        case "fa-behance":
            return "f1b4";
        case "fa-behance-square":
            return "f1b5";
        case "fa-steam":
            return "f1b6";
        case "fa-steam-square":
            return "f1b7";
        case "fa-recycle":
            return "f1b8";
        case "fa-automobile:before,.fa-car":
            return "f1b9";
        case "fa-cab:before,.fa-taxi":
            return "f1ba";
        case "fa-tree":
            return "f1bb";
        case "fa-spotify":
            return "f1bc";
        case "fa-deviantart":
            return "f1bd";
        case "fa-soundcloud":
            return "f1be";
        case "fa-database":
            return "f1c0";
        case "fa-file-pdf-o":
            return "f1c1";
        case "fa-file-word-o":
            return "f1c2";
        case "fa-file-excel-o":
            return "f1c3";
        case "fa-file-powerpoint-o":
            return "f1c4";
        case "fa-file-photo-o:before,.fa-file-picture-o:before,.fa-file-image-o":
            return "f1c5";
        case "fa-file-zip-o:before,.fa-file-archive-o":
            return "f1c6";
        case "fa-file-sound-o:before,.fa-file-audio-o":
            return "f1c7";
        case "fa-file-movie-o:before,.fa-file-video-o":
            return "f1c8";
        case "fa-file-code-o":
            return "f1c9";
        case "fa-vine":
            return "f1ca";
        case "fa-codepen":
            return "f1cb";
        case "fa-jsfiddle":
            return "f1cc";
        case "fa-life-bouy:before,.fa-life-buoy:before,.fa-life-saver:before,.fa-support:before,.fa-life-ring":
            return "f1cd";
        case "fa-circle-o-notch":
            return "f1ce";
        case "fa-ra:before,.fa-resistance:before,.fa-rebel":
            return "f1d0";
        case "fa-ge:before,.fa-empire":
            return "f1d1";
        case "fa-git-square":
            return "f1d2";
        case "fa-git":
            return "f1d3";
        case "fa-y-combinator-square:before,.fa-yc-square:before,.fa-hacker-news":
            return "f1d4";
        case "fa-tencent-weibo":
            return "f1d5";
        case "fa-qq":
            return "f1d6";
        case "fa-wechat:before,.fa-weixin":
            return "f1d7";
        case "fa-send:before,.fa-paper-plane":
            return "f1d8";
        case "fa-send-o:before,.fa-paper-plane-o":
            return "f1d9";
        case "fa-history":
            return "f1da";
        case "fa-circle-thin":
            return "f1db";
        case "fa-header":
            return "f1dc";
        case "fa-paragraph":
            return "f1dd";
        case "fa-sliders":
            return "f1de";
        case "fa-share-alt":
            return "f1e0";
        case "fa-share-alt-square":
            return "f1e1";
        case "fa-bomb":
            return "f1e2";
        case "fa-soccer-ball-o:before,.fa-futbol-o":
            return "f1e3";
        case "fa-tty":
            return "f1e4";
        case "fa-binoculars":
            return "f1e5";
        case "fa-plug":
            return "f1e6";
        case "fa-slideshare":
            return "f1e7";
        case "fa-twitch":
            return "f1e8";
        case "fa-yelp":
            return "f1e9";
        case "fa-newspaper-o":
            return "f1ea";
        case "fa-wifi":
            return "f1eb";
        case "fa-calculator":
            return "f1ec";
        case "fa-paypal":
            return "f1ed";
        case "fa-google-wallet":
            return "f1ee";
        case "fa-cc-visa":
            return "f1f0";
        case "fa-cc-mastercard":
            return "f1f1";
        case "fa-cc-discover":
            return "f1f2";
        case "fa-cc-amex":
            return "f1f3";
        case "fa-cc-paypal":
            return "f1f4";
        case "fa-cc-stripe":
            return "f1f5";
        case "fa-bell-slash":
            return "f1f6";
        case "fa-bell-slash-o":
            return "f1f7";
        case "fa-trash":
            return "f1f8";
        case "fa-copyright":
            return "f1f9";
        case "fa-at":
            return "f1fa";
        case "fa-eyedropper":
            return "f1fb";
        case "fa-paint-brush":
            return "f1fc";
        case "fa-birthday-cake":
            return "f1fd";
        case "fa-area-chart":
            return "f1fe";
        case "fa-pie-chart":
            return "f200";
        case "fa-line-chart":
            return "f201";
        case "fa-lastfm":
            return "f202";
        case "fa-lastfm-square":
            return "f203";
        case "fa-toggle-off":
            return "f204";
        case "fa-toggle-on":
            return "f205";
        case "fa-bicycle":
            return "f206";
        case "fa-bus":
            return "f207";
        case "fa-ioxhost":
            return "f208";
        case "fa-angellist":
            return "f209";
        case "fa-cc":
            return "f20a";
        case "fa-shekel:before,.fa-sheqel:before,.fa-ils":
            return "f20b";
        case "fa-meanpath":
            return "f20c";
        case "fa-buysellads":
            return "f20d";
        case "fa-connectdevelop":
            return "f20e";
        case "fa-dashcube":
            return "f210";
        case "fa-forumbee":
            return "f211";
        case "fa-leanpub":
            return "f212";
        case "fa-sellsy":
            return "f213";
        case "fa-shirtsinbulk":
            return "f214";
        case "fa-simplybuilt":
            return "f215";
        case "fa-skyatlas":
            return "f216";
        case "fa-cart-plus":
            return "f217";
        case "fa-cart-arrow-down":
            return "f218";
        case "fa-diamond":
            return "f219";
        case "fa-ship":
            return "f21a";
        case "fa-user-secret":
            return "f21b";
        case "fa-motorcycle":
            return "f21c";
        case "fa-street-view":
            return "f21d";
        case "fa-heartbeat":
            return "f21e";
        case "fa-venus":
            return "f221";
        case "fa-mars":
            return "f222";
        case "fa-mercury":
            return "f223";
        case "fa-intersex:before,.fa-transgender":
            return "f224";
        case "fa-transgender-alt":
            return "f225";
        case "fa-venus-double":
            return "f226";
        case "fa-mars-double":
            return "f227";
        case "fa-venus-mars":
            return "f228";
        case "fa-mars-stroke":
            return "f229";
        case "fa-mars-stroke-v":
            return "f22a";
        case "fa-mars-stroke-h":
            return "f22b";
        case "fa-neuter":
            return "f22c";
        case "fa-genderless":
            return "f22d";
        case "fa-facebook-official":
            return "f230";
        case "fa-pinterest-p":
            return "f231";
        case "fa-whatsapp":
            return "f232";
        case "fa-server":
            return "f233";
        case "fa-user-plus":
            return "f234";
        case "fa-user-times":
            return "f235";
        case "fa-hotel:before,.fa-bed":
            return "f236";
        case "fa-viacoin":
            return "f237";
        case "fa-train":
            return "f238";
        case "fa-subway":
            return "f239";
        case "fa-medium":
            return "f23a";
        case "fa-yc:before,.fa-y-combinator":
            return "f23b";
        case "fa-optin-monster":
            return "f23c";
        case "fa-opencart":
            return "f23d";
        case "fa-expeditedssl":
            return "f23e";
        case "fa-battery-4:before,.fa-battery:before,.fa-battery-full":
            return "f240";
        case "fa-battery-3:before,.fa-battery-three-quarters":
            return "f241";
        case "fa-battery-2:before,.fa-battery-half":
            return "f242";
        case "fa-battery-1:before,.fa-battery-quarter":
            return "f243";
        case "fa-battery-0:before,.fa-battery-empty":
            return "f244";
        case "fa-mouse-pointer":
            return "f245";
        case "fa-i-cursor":
            return "f246";
        case "fa-object-group":
            return "f247";
        case "fa-object-ungroup":
            return "f248";
        case "fa-sticky-note":
            return "f249";
        case "fa-sticky-note-o":
            return "f24a";
        case "fa-cc-jcb":
            return "f24b";
        case "fa-cc-diners-club":
            return "f24c";
        case "fa-clone":
            return "f24d";
        case "fa-balance-scale":
            return "f24e";
        case "fa-hourglass-o":
            return "f250";
        case "fa-hourglass-1:before,.fa-hourglass-start":
            return "f251";
        case "fa-hourglass-2:before,.fa-hourglass-half":
            return "f252";
        case "fa-hourglass-3:before,.fa-hourglass-end":
            return "f253";
        case "fa-hourglass":
            return "f254";
        case "fa-hand-grab-o:before,.fa-hand-rock-o":
            return "f255";
        case "fa-hand-stop-o:before,.fa-hand-paper-o":
            return "f256";
        case "fa-hand-scissors-o":
            return "f257";
        case "fa-hand-lizard-o":
            return "f258";
        case "fa-hand-spock-o":
            return "f259";
        case "fa-hand-pointer-o":
            return "f25a";
        case "fa-hand-peace-o":
            return "f25b";
        case "fa-trademark":
            return "f25c";
        case "fa-registered":
            return "f25d";
        case "fa-creative-commons":
            return "f25e";
        case "fa-gg":
            return "f260";
        case "fa-gg-circle":
            return "f261";
        case "fa-tripadvisor":
            return "f262";
        case "fa-odnoklassniki":
            return "f263";
        case "fa-odnoklassniki-square":
            return "f264";
        case "fa-get-pocket":
            return "f265";
        case "fa-wikipedia-w":
            return "f266";
        case "fa-safari":
            return "f267";
        case "fa-chrome":
            return "f268";
        case "fa-firefox":
            return "f269";
        case "fa-opera":
            return "f26a";
        case "fa-internet-explorer":
            return "f26b";
        case "fa-tv:before,.fa-television":
            return "f26c";
        case "fa-contao":
            return "f26d";
        case "fa-500px":
            return "f26e";
        case "fa-amazon":
            return "f270";
        case "fa-calendar-plus-o":
            return "f271";
        case "fa-calendar-minus-o":
            return "f272";
        case "fa-calendar-times-o":
            return "f273";
        case "fa-calendar-check-o":
            return "f274";
        case "fa-industry":
            return "f275";
        case "fa-map-pin":
            return "f276";
        case "fa-map-signs":
            return "f277";
        case "fa-map-o":
            return "f278";
        case "fa-map":
            return "f279";
        case "fa-commenting":
            return "f27a";
        case "fa-commenting-o":
            return "f27b";
        case "fa-houzz":
            return "f27c";
        case "fa-vimeo":
            return "f27d";
        case "fa-black-tie":
            return "f27e";
        case "fa-fonticons":
            return "f280";
        case "fa-reddit-alien":
            return "f281";
        case "fa-edge":
            return "f282";
        case "fa-credit-card-alt":
            return "f283";
        case "fa-codiepie":
            return "f284";
        case "fa-modx":
            return "f285";
        case "fa-fort-awesome":
            return "f286";
        case "fa-usb":
            return "f287";
        case "fa-product-hunt":
            return "f288";
        case "fa-mixcloud":
            return "f289";
        case "fa-scribd":
            return "f28a";
        case "fa-pause-circle":
            return "f28b";
        case "fa-pause-circle-o":
            return "f28c";
        case "fa-stop-circle":
            return "f28d";
        case "fa-stop-circle-o":
            return "f28e";
        case "fa-shopping-bag":
            return "f290";
        case "fa-shopping-basket":
            return "f291";
        case "fa-hashtag":
            return "f292";
        case "fa-bluetooth":
            return "f293";
        case "fa-bluetooth-b":
            return "f294";
        case "fa-percent":
            return "f295";
        case "fa-gitlab":
            return "f296";
        case "fa-wpbeginner":
            return "f297";
        case "fa-wpforms":
            return "f298";
        case "fa-envira":
            return "f299";
        case "fa-universal-access":
            return "f29a";
        case "fa-wheelchair-alt":
            return "f29b";
        case "fa-question-circle-o":
            return "f29c";
        case "fa-blind":
            return "f29d";
        case "fa-audio-description":
            return "f29e";
        case "fa-volume-control-phone":
            return "f2a0";
        case "fa-braille":
            return "f2a1";
        case "fa-assistive-listening-systems":
            return "f2a2";
        case "fa-asl-interpreting:before,.fa-american-sign-language-interpreting":
            return "f2a3";
        case "fa-deafness:before,.fa-hard-of-hearing:before,.fa-deaf":
            return "f2a4";
        case "fa-glide":
            return "f2a5";
        case "fa-glide-g":
            return "f2a6";
        case "fa-signing:before,.fa-sign-language":
            return "f2a7";
        case "fa-low-vision":
            return "f2a8";
        case "fa-viadeo":
            return "f2a9";
        case "fa-viadeo-square":
            return "f2aa";
        case "fa-snapchat":
            return "f2ab";
        case "fa-snapchat-ghost":
            return "f2ac";
        case "fa-snapchat-square":
            return "f2ad";
        case "fa-pied-piper":
            return "f2ae";
        case "fa-first-order":
            return "f2b0";
        case "fa-yoast":
            return "f2b1";
        case "fa-themeisle":
            return "f2b2";
        case "fa-google-plus-circle:before,.fa-google-plus-official":
            return "f2b3";
        case "fa-fa:before,.fa-font-awesome":
            return "f2b4";
        case "fa-handshake-o":
            return "f2b5";
        case "fa-envelope-open":
            return "f2b6";
        case "fa-envelope-open-o":
            return "f2b7";
        case "fa-linode":
            return "f2b8";
        case "fa-address-book":
            return "f2b9";
        case "fa-address-book-o":
            return "f2ba";
        case "fa-vcard:before,.fa-address-card":
            return "f2bb";
        case "fa-vcard-o:before,.fa-address-card-o":
            return "f2bc";
        case "fa-user-circle":
            return "f2bd";
        case "fa-user-circle-o":
            return "f2be";
        case "fa-user-o":
            return "f2c0";
        case "fa-id-badge":
            return "f2c1";
        case "fa-drivers-license:before,.fa-id-card":
            return "f2c2";
        case "fa-drivers-license-o:before,.fa-id-card-o":
            return "f2c3";
        case "fa-quora":
            return "f2c4";
        case "fa-free-code-camp":
            return "f2c5";
        case "fa-telegram":
            return "f2c6";
        case "fa-thermometer-4:before,.fa-thermometer:before,.fa-thermometer-full":
            return "f2c7";
        case "fa-thermometer-3:before,.fa-thermometer-three-quarters":
            return "f2c8";
        case "fa-thermometer-2:before,.fa-thermometer-half":
            return "f2c9";
        case "fa-thermometer-1:before,.fa-thermometer-quarter":
            return "f2ca";
        case "fa-thermometer-0:before,.fa-thermometer-empty":
            return "f2cb";
        case "fa-shower":
            return "f2cc";
        case "fa-bathtub:before,.fa-s15:before,.fa-bath":
            return "f2cd";
        case "fa-podcast":
            return "f2ce";
        case "fa-window-maximize":
            return "f2d0";
        case "fa-window-minimize":
            return "f2d1";
        case "fa-window-restore":
            return "f2d2";
        case "fa-times-rectangle:before,.fa-window-close":
            return "f2d3";
        case "fa-times-rectangle-o:before,.fa-window-close-o":
            return "f2d4";
        case "fa-bandcamp":
            return "f2d5";
        case "fa-grav":
            return "f2d6";
        case "fa-etsy":
            return "f2d7";
        case "fa-imdb":
            return "f2d8";
        case "fa-ravelry":
            return "f2d9";
        case "fa-eercast":
            return "f2da";
        case "fa-microchip":
            return "f2db";
        case "fa-snowflake-o":
            return "f2dc";
        case "fa-superpowers":
            return "f2dd";
        case "fa-wpexplorer":
            return "f2de";
        case "fa-meetup":
            return "f2e0";
    }
};
